### ISSUE TITLE
Tokenomics price formulas in the SDK

### ISSUE THREAD

**Issue by roxdanila** [NexusMutual/sdk#69] opened 2023-09-15 09:27 UTC
- Calculate price (this includes price impact):
  - swap ETH -> NXM (calculateNXMForETH(ethInput)) 
      ```
      k = state.nxmA * state.eth
      ethNew = state.eth + ethInput
      nxmANew = k / ethNew
      nxmOut = nxmANew - state.nxmA
      ```
      
  - swap ETH -> NXM (calculateETHForExactNXM(nxmOutput)) 
    ```
     k = state.nxmA * state.eth
     nxmANew = nxmA - nxmOutput
     ethNew = k / nxmANew
     ethInput = ethNew - state.Eth
    ```
    
  - swap NXM -> ETH (calculateETHForNXM nxmInput))
      ```
      k = state.nxmB * state.eth
      nxmBNew = state.nxmB + nxmInput
      ethNew = k / nxmBNewethNew
      ethOut = state.eth - ethNew
      ```
      
  - swap NXM -> ETH (calculateNXMForExactETH(ethOutput)) 
      ```
      k = state.nxmB * state.eth
      ethNew = state.eth - ethOutput
      nxmBNew = k / ethNew
      nxmIn = nxmBNew - state.nxmB
      ```
      
- Calculate spot prices (don't include price impact):
    ```
        State state = getReserves();
        return (
          1 ether * state.eth / state.nxmA,  // spot price A
          1 ether * state.eth / state.nxmB  // spot price B
        );
    ```
  
- Calculate price impact (expressed as a %): 
  - swap ETH -> NXM (buy NXM)  
     ```
     priceImpactA = abs (1 - calculateNXMForETH() / spotPriceA) * 100
  - swap NXM -> ETH (sell NXM)  
     ```
     priceImpactB = abs (1 - calculateETHForNXM() / spotPriceB) * 100
     ```

**Comment by Gideonnn** [comment] 2023-10-23 10:44
Done and merged, just need some tests to make sure they keep working as intended. For those I need some assistance, so I made another issue [here](https://github.com/NexusMutual/sdk/issues/72).

**Comment by roxdanila** [comment] 2023-10-25 14:19
L.E.: Anatol suggested the following naming for the 4 calculate functions:
```
nxm -> eth
calculateExactNxmForEth
calculateNxmForExactEth

eth -> nxm
calculateExactEthForNxm
calculateEthForExactNxm
```

**Closed** 2023-11-02 11:02 UTC
Labels: feature, high
